services:
  alpha:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: alpha-node
    volumes:
      - alpha-data:/root/.alpha
      # Mount custom configuration if available
      - ./config:/config:ro
    ports:
      - "127.0.0.1:8589:8589"  # RPC port (localhost only)
      - "8590:8590"  # P2P port (public)
    restart: unless-stopped

volumes:
  alpha-data:
    # This volume persists blockchain data between container restarts